# Generated by Django 5.0.6 on 2024-07-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_tag_produit_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
