# Generated by Django 5.0.6 on 2024-07-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.TextField(default='Adresse par défaut'),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='nom.prenom@gmail.com ', max_length=254),
        ),
    ]
